# This workflow will upload a Python Package to a private repository when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package to Private Repository

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build release distributions
        run: |
          uv build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  private-repo-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      contents: read

    # Dedicated environments with protections for publishing are strongly recommended.
    environment:
      name: private-repo
      url: https://app.dataops.live/api/v4/projects/5844/packages/pypi

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Publish release distributions to private repository
        env:
          UV_PUBLISH_USERNAME: ${{ secrets.PRIVATE_REPO_USERNAME }}
          UV_PUBLISH_PASSWORD: ${{ secrets.PRIVATE_REPO_PASSWORD }}
        run: |
          uv publish --publish-url https://app.dataops.live/api/v4/projects/5844/packages/pypi dist/*
